# Generated by Django 2.2 on 2023-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_category',
            field=models.CharField(choices=[('S', 'Sedan'), ('H', 'Hatchback'), ('C', 'Cabriolet'), ('E', 'Estate'), ('Sp', 'Sport'), ('P', 'Pickup'), ('M', 'Micro')], default='Sedan', max_length=1),
        ),
    ]
