# Generated by Django 2.2 on 2023-02-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('engine_size', models.FloatField(default=0)),
                ('motorcycle_category', models.CharField(choices=[('S', 'Scooter'), ('Ch', 'Chopper'), ('C', 'Cross'), ('D', 'Dirt Bike'), ('Sp', 'Sport'), ('St', 'Street'), ('E', 'Enduro'), ('Tu', 'Touring')], default='', max_length=2)),
                ('horse_power', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('number_of_tires', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='', max_length=1)),
                ('year', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('description', models.TextField(default='')),
                ('quantity', models.FloatField(default=0)),
            ],
        ),
    ]
