# Generated by Django 2.2 on 2023-02-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_remove_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('M', 'Mercedes-Benz'), ('A', 'Audi'), ('B', 'BMW'), ('P', 'Porsche'), ('V', 'VW'), ('S', 'Smart'), ('MB', 'Maybach')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles_api.Manufacturer'),
        ),
    ]
