# Generated by Django 2.2 on 2023-02-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_motorcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='number_of_tires',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default='', max_length=2),
        ),
    ]
