# Generated by Django 2.2 on 2023-02-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20230209_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='number_of_tires',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default='', max_length=1),
        ),
    ]
