# Generated by Django 2.2 on 2023-02-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20230205_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
