# Generated by Django 2.2 on 2023-02-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_auto_20230209_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
