# Generated by Django 2.2 on 2023-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0011_auto_20230209_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
