# Generated by Django 2.2 on 2023-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_auto_20230209_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='number_of_cylinders',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('6', 6)], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='motorcycle_category',
            field=models.CharField(choices=[('S', 'Scooter'), ('Ch', 'Chopper'), ('C', 'Cross'), ('D', 'Dirt Bike'), ('Sp', 'Sport'), ('St', 'Street'), ('E', 'Enduro'), ('Tu', 'Touring'), ('Tr', '3 Wheeler'), ('Fr', '4 Wheeler')], default='', max_length=2),
        ),
    ]
