# Generated by Django 2.2 on 2023-02-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0014_auto_20230209_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[(1, 'New'), (0, 'Used')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='condition',
            field=models.CharField(choices=[(1, 'New'), (0, 'Used')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
