# Generated by Django 2.2 on 2023-02-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0015_auto_20230209_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motorcycle',
        ),
    ]
