# Generated by Django 2.2 on 2023-02-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0017_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[(1, 'New'), (2, 'Used')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
