# Generated by Django 2.2 on 2023-02-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0018_auto_20230211_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
