# Generated by Django 2.2 on 2023-02-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0019_auto_20230211_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='', max_length=4),
        ),
    ]
