# Generated by Django 2.2 on 2023-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0020_auto_20230211_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
